language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - flake8 retryz test
    - py.test --cov=retryz --junit-xml=junit-result.xml --cov-report term-missing test
after_success:
    - coveralls
notifications:
    email:
        - jealous@163.com